### ISSUE TITLE
Unable to unset `cursor` property

### ISSUE THREAD

**Issue by bobby** [inlet/react-pixi#29]
### Description

I am trying to temporarily set the cursor style of a child element during an interaction, and then to remove the child cursor style so that the cursor's appearance reverts to that set on the parent element when the interaction is completed.  However, currently I'm unable to set the `cursor` property to `null` due to https://github.com/inlet/react-pixi/blob/master/src/utils/props.js#L113.  I would expect to be warned in this case, but still be able to set the property to `null` if I wanted to.

This issue doesn't appear immediately (possibly indicating that the `cursor` default of `'auto'` isn't applied initially).  Initially, the parent's cursor styles are presented when mousing over the child element.  However, once the child element's `cursor` property is set to anything (including `'auto'`!), the parent's cursor style is never again presented.

I believe that setting the `cursor` property's value to `'auto'` is incorrect, and that there should be no default for this property.  Furthermore, as the developer, I shouldn't be prevented from setting any property to `null` if I so choose.

I am aware that I'll be able to work around this issue by setting the new `overwriteProps` property to `true` in future releases.  However, there is no work-around for version `0.1.0`.  When is the next release scheduled?

### Steps to reproduce

1. Create a parent element with a single child element
2. Set the parent's `cursor` property to e.g. `'crosshair'`, and observe that this style is presented when mousing over the child element
3. Set the child element's `cursor` property to e.g. `'zoom-in'`, and observe that this style is now presented when mousing over the child element, rather than the parent's `'crosshair'` style.
4. Set the child element's `cursor` to `null`, observe a console warning indicating that ReactPixi won't set the `cursor` property to `null` but rather will use the default value of `'auto'`, and observe that the default cursor style of `'auto'` is presented when mousing over the child element, rather than the parent's `'crosshair'` style.
5. Try setting the child element's `cursor` to `'inherit'`, `'default'`, `'initial'`, etc. and observe that the parent's cursor style isn't presented regardless of the value of the child's `cursor` property.

### Additional info

- `@inlet/react-pixi` version: 0.1.0
- `React` version: 16.4.1
- `ReactDOM` version: 16.4.1
- `PIXI` version: 4.8.1

**Comment by inlet** [comment]
Hi @bobby,

Thanks for pointing out, I've just merged a PR with a fix. 

Here is a working demo with the patch applied (v0.1.2):

https://codepen.io/inlet/pen/11c8037ae335964a74daeeb0409f292f/

**Comment by bobby** [comment]
@inlet thank you very much for the fast resolution of this issue, and for releasing the fix in a new version!

Note that the console warning is still present when setting the `cursor` value back to `null` in your codepen.  I wouldn't consider this a warning situation, but rather a normal use of the library.

**Comment by inlet** [comment]
Welcome! 

You are right, these warnings indicates that the value is set back to default, which is `null` for prop `cursor`. Warning messages are only shown in development though.
